apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "mypipeline", "namespace": "mypro", "kind":
      "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    app: jenkins-pipeline-development
    name: mypipeline-test
    template: application-template-development-pipeline
  name: mypipeline-test
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
        stage 'build'
        openshiftBuild(buildConfig: 'mypipeline', showBuildLogs: 'true', namespace: 'mypro')
        stage 'deploy'
        openshiftDeploy(deploymentConfig: 'mypipeline', namespace: 'mypro')
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0