def appName = "${APP_NAME}"
def project = ""
def pom
node {
    stage("Initialize") {
        project = env.PROJECT_NAME
    }
}
node("maven") {
    stage("Checkout") {
        git url: "${GIT_SOURCE_URL}", branch: "${GIT_SOURCE_REF}"
    }
    stage("Gather buildfacts") {
        pom = readMavenPom file: 'pom.xml'
    }
    stage("Build JAR") {
        sh "mvn clean package -Popenshift"
        stash name: "jar", includes: "target/app.jar"
    }
}

node {
    stage("Build Image") {
        unstash name: "jar"
        sh "oc start-build ${appName}-docker --from-file=target/app.jar --follow -n ${project}"
    }
    stage("Deploy") {
        timeout(time: 5, unit: 'MINUTES') {
            input message: "Deploy new Version?", ok: "Deploy"
        }
        openshiftDeploy deploymentConfig: appName, namespace: project
    }
}