def appName = "springboot-sample-app"
def project = ""
def pom
node {
    stage("Initialize") {
        project = env.PROJECT_NAME
    }
}
node("maven") {
    stage("Checkout") {
        git url: "https://github.com/jorgemoralespou/springboot-sample-app.git", branch: "master"
    }
    stage("Gather buildfacts") {
        pom = readMavenPom file: 'pom.xml'
    }
    stage("Build JAR") {
        sh "mvn clean package -Popenshift"
        stash name: "jar", includes: "target/app.jar"
    }
}

node {
    stage("Build Image") {
        unstash name: "jar"
        sh "oc start-build ${appName}-docker --from-file=target/app.jar --follow -n ${project}"
    }
    stage("Deploy") {
        openshiftDeploy deploymentConfig: appName, namespace: project
    }
    stage("Tag image") {
        openshiftTag srcStream: appName, srcTag: "latest", destStream: appName, destTag: pom.version, alias: "false"
    }
    stage("Print env variables") {
        sh "printenv"
    }
}
